// packages/vue/src/CaptchaFox.vue
<script setup lang="ts">
import { isApiReady, loadCaptchaScript } from '@captchafox/internal';
import type { WidgetApi, WidgetOptions } from '@captchafox/types';
import { onMounted, ref, watch } from 'vue';

export type CaptchaFoxProps = Pick<
  WidgetOptions,
  'sitekey' | 'lang' | 'mode' | 'theme' | 'i18n' | 'hideClose'
> & {
  modelValue?: string;
  containerClass?: string;
  nonce?: string;
};

export type CaptchaFoxInstance = Omit<WidgetApi, 'render'>;

const widgetId = ref<string | undefined>();
const container = ref<HTMLDivElement | null>(null);

const props = defineProps<CaptchaFoxProps>();

const emit = defineEmits<{
  /** Called with the response token after successful verification. */
  verify: [token: string];
  /** Called after the challenge expires. */
  expire: [];
  /** Called when an error occurs. */
  error: [error?: Error | string];
  /** Called when the challenge was closed. */
  close: [];
  /** Called after unsuccessful verification. */
  fail: [];
  /** Called after the widget has been loaded */
  load: [];
  /** Called after the challenge opened */
  challengeOpen: [];
  /** Called after the challenge changed */
  challengeChange: [];
  'update:modelValue': [token: string];
}>();

defineExpose({
  getResponse() {
    if (!isApiReady() || !widgetId.value) {
      console.warn('[CaptchaFox] Widget has not been loaded');
      return '';
    }

    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    return window.captchafox!.getResponse(widgetId.value);
  },
  reset() {
    if (!isApiReady() || !widgetId.value) {
      console.warn('[CaptchaFox] Widget has not been loaded');
      return;
    }

    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    window.captchafox!.reset(widgetId.value);
  },
  remove() {
    if (!isApiReady() || !widgetId.value) {
      console.warn('[CaptchaFox] Widget has not been loaded');
      return;
    }

    widgetId.value = '';
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    window.captchafox!.remove(widgetId.value);
  },
  execute: () => {
    if (!isApiReady() || !widgetId.value) {
      return Promise.reject('[CaptchaFox] Widget has not been loaded');
    }

    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    return window.captchafox!.execute(widgetId.value);
  }
});

const renderCaptcha = async (): Promise<void> => {
  window.captchafox?.remove(widgetId.value);

  const newWidgetId = await window.captchafox?.render(container.value as HTMLElement, {
    lang: props.lang,
    sitekey: props.sitekey,
    mode: props.mode,
    theme: props.theme,
    i18n: props.i18n,
    hideClose: props.hideClose,
    onError: (error) => emit('error', error),
    onFail: () => emit('fail'),
    onClose: () => emit('close'),
    onVerify: (token: string) => {
      emit('verify', token);
      emit('update:modelValue', token);
    },
    onExpire: () => emit('expire'),
    onChallengeChange: () => emit('challengeChange'),
    onChallengeOpen: () => emit('challengeOpen')
  });

  widgetId.value = newWidgetId;
  emit('load');
};

onMounted(() => {
  loadCaptchaScript({ nonce: props.nonce })
    .then(async () => {
      if (isApiReady()) {
        await renderCaptcha();
      }
    })
    .catch((error) => {
      emit('error', error);
      console.error('[CaptchaFox] Could not load script:', error);
    });
});

watch(
  [
    () => props.lang,
    () => props.mode,
    () => props.sitekey,
    () => props.theme,
    () => props.hideClose
  ],
  async () => {
    await renderCaptcha();
  }
);
</script>

<template>
  <div ref="container" :class="containerClass" />
</template>

// packages/angular/src/captchafox.component.ts
import { isPlatformBrowser, isPlatformServer } from '@angular/common';
import {
  Component,
  ElementRef,
  EventEmitter,
  Inject,
  Input,
  NgZone,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  PLATFORM_ID,
  ViewChild,
  forwardRef
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import type { Theme, WidgetDisplayMode, WidgetI18nConfig } from '@captchafox/types';
import { Subscription, from } from 'rxjs';
import { CAPTCHA_CONFIG, CaptchaConfig } from './config';
import { isApiReady, loadCaptchaScript } from './loader';

type MarkFunctionProperties<Component> = {
  // eslint-disable-next-line @typescript-eslint/ban-types
  [Key in keyof Component]: Component[Key] extends Function ? never : Key;
};
type ExcludeFunctionPropertyNames<T> = MarkFunctionProperties<T>[keyof T];
type ExcludeFunctions<T> = Pick<T, ExcludeFunctionPropertyNames<T>>;
type NgChanges<Component, Props = ExcludeFunctions<Component>> = {
  [Key in keyof Props]: {
    previousValue: Props[Key];
    currentValue: Props[Key];
    firstChange: boolean;
    isFirstChange(): boolean;
  };
};

@Component({
  selector: 'ngx-captchafox',
  template: `<div #container class="ngx-captchafox-container"></div>`,
  styles: [],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CaptchaFoxComponent),
      multi: true
    }
  ]
})
export class CaptchaFoxComponent implements OnInit, OnDestroy, OnChanges, ControlValueAccessor {
  @Input() siteKey?: string;
  @Input() lang?: string;
  @Input() mode?: WidgetDisplayMode;
  @Input() theme?: Theme;
  @Input() nonce?: string;
  @Input() i18n?: WidgetI18nConfig;
  @Input() hideClose?: boolean;

  @Output() load: EventEmitter<void> = new EventEmitter<void>();
  @Output() verify: EventEmitter<string> = new EventEmitter<string>();
  @Output() expire: EventEmitter<void> = new EventEmitter<void>();
  @Output() error: EventEmitter<Error | string | undefined> = new EventEmitter<
    Error | string | undefined
  >();
  @Output() fail: EventEmitter<void> = new EventEmitter<void>();
  @Output() close: EventEmitter<void> = new EventEmitter<void>();
  @Output() challengeOpen: EventEmitter<void> = new EventEmitter<void>();
  @Output() challengeChange: EventEmitter<void> = new EventEmitter<void>();

  @ViewChild('container', { static: true }) containerEl?: ElementRef;

  private widgetId?: string;
  private scriptLoader$?: Subscription;

  private _onChange?: (token: string | null) => void;
  private _onTouched?: () => void;
  private _responseToken: string | null = null;

  constructor(
    @Inject(CAPTCHA_CONFIG) private config: CaptchaConfig,
    @Inject(PLATFORM_ID) private platformId: object,
    private zone: NgZone
  ) {}

  async ngOnChanges(changes: NgChanges<CaptchaFoxComponent>) {
    if (
      !changes.siteKey?.isFirstChange() &&
      !changes.mode?.isFirstChange() &&
      !changes.lang?.isFirstChange() &&
      !changes.theme?.isFirstChange() &&
      !changes.hideClose?.isFirstChange()
    ) {
      window.captchafox?.remove(this.widgetId);
      await this.renderCaptcha();
    }
  }

  ngOnInit(): void {
    if (isPlatformServer(this.platformId)) {
      return;
    }

    this.scriptLoader$ = from(loadCaptchaScript({ nonce: this.nonce })).subscribe({
      next: async () => {
        this.load.emit();
        try {
          await this.renderCaptcha();
        } catch (error) {
          this.error.emit(error as Error);
        }
      },
      error: (error) => {
        this.error.emit(error);
        console.error('[CaptchaFox] Could not load script:', error);
      }
    });
  }

  ngOnDestroy(): void {
    if (isPlatformServer(this.platformId)) {
      return;
    }

    this.scriptLoader$?.unsubscribe();
  }

  private async renderCaptcha() {
    if (!isApiReady() || !this.containerEl) {
      return;
    }

    const newWidgetId = await window.captchafox?.render(this.containerEl.nativeElement, {
      lang: this.lang ?? this.config.language,
      sitekey: this.siteKey ?? this.config.siteKey ?? '',
      mode: this.mode ?? this.config.mode,
      theme: this.theme ?? this.config.theme,
      i18n: this.i18n ?? this.config.i18n,
      hideClose: this.hideClose ?? this.config.hideClose,
      onError: (error) => {
        this.zone.run(() => this.error.emit(error));
      },
      onFail: () => {
        this.zone.run(() => this.fail.emit());
      },
      onClose: () => {
        this.zone.run(() => this.close.emit());
      },
      onVerify: (token: string) => {
        this.zone.run(() => {
          this.writeValue(token);
          this.verify.emit(token);
        });
      },
      onExpire: () => {
        this.zone.run(() => this.expire.emit());
      },
      onChallengeChange: () => {
        this.zone.run(() => this.challengeChange.emit());
      },
      onChallengeOpen: () => {
        this.zone.run(() => this.challengeOpen.emit());
      }
    });

    this.widgetId = newWidgetId;
  }

  get value(): string | null {
    return this._responseToken;
  }

  writeValue(value: string | null): void {
    this._responseToken = value;
    this._onChange?.(value);
    this._onTouched?.();

    // handle form reset
    if (!value && isPlatformBrowser(this.platformId)) {
      window.captchafox?.reset(this.widgetId);
    }
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  registerOnChange(fn: any): void {
    this._onChange = fn;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  registerOnTouched(fn: any): void {
    this._onTouched = fn;
  }
}
